### ISSUE TITLE
Launcher Error Invalid response: 500 Internal Server Error

### ISSUE THREAD

**Issue by ghltshubh** [chaoleili/jupyterlab_tensorboard#17]
I am running jupyter lab on a server and accessing it via tunneling. I have installed everything the environment but getting 

```
Launcher Error
Invalid response: 500 Internal Server Error

```

**Comment by rjafarau** [comment]
The same issue

**Comment by edoardogiacomello** [comment]
Same issue here. I don't know if it can be related to the jupyterlab version, but it stopped working for me when updating from 0.35.6 to 1.2.4.

**Comment by ruralscenery** [comment]
500 Internal Server Error

Traceback (most recent call last):↵ 
 File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute↵    
result = method(*self.path_args, **self.path_kwargs)↵  
File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 3178, in wrapper↵    
return method(self, *args, **kwargs)↵  
File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post↵   
 .new_instance(data["logdir"], reload_interval=reload_interval)↵  
File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 221, in new_instance↵    
purge_orphaned_data=purge_orphaned_data)↵  
File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 47, in create_tb_app↵    
tensorboard.assets_zip_provider)↵  
File "/opt/conda/lib/python3.7/site-packages/tensorboard/backend/application.py", line 147, in standard_tensorboard_wsgi↵    
flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer↵  
File "/opt/conda/lib/python3.7/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 165, in TensorBoardWSGIApp_2x↵    
window_title=flags.window_title)↵
TypeError: __init__() got an unexpected keyword argument 'db_connection_provider'↵"

**Comment by octavd** [comment]
Hello,

I can confirm i have the same error -> 500 Internal Server Error

```

Traceback (most recent call last):
--
  | File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1701, in _execute
  | result = method(*self.path_args, **self.path_kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 3178, in wrapper
  | return method(self, *args, **kwargs)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/api_handlers.py", line 40, in post
  | .new_instance(data["logdir"], reload_interval=reload_interval)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 221, in new_instance
  | purge_orphaned_data=purge_orphaned_data)
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 47, in create_tb_app
  | tensorboard.assets_zip_provider)
  | File "/opt/app-root/lib/python3.6/site-packages/tensorboard/backend/application.py", line 147, in standard_tensorboard_wsgi
  | flags, plugin_loaders, data_provider, assets_zip_provider, multiplexer
  | File "/opt/app-root/lib/python3.6/site-packages/jupyter_tensorboard/tensorboard_manager.py", line 165, in TensorBoardWSGIApp_2x
  | window_title=flags.window_title)
  | TypeError: __init__() got an unexpected keyword argument 'db_connection_provider'
```

Could you please advise? :)

**Comment by octavd** [comment]
I've found a solution to make it work.
I was missing from ```pip``` -> ```tensorboard```

Here you can find the requirements:
```
tensorflow==2.1.0
jupyter-tensorboard==0.2.0
tensorflow-estimator==2.1.0
tensorboard==2.1.0
```
And for ```jupyter```:
```
jupyter-client         6.1.3      
jupyter-core           4.6.3      
jupyter-kernel-gateway 2.4.0      
jupyter-telemetry      0.1.0      
jupyter-tensorboard    0.2.0      
jupyterhub             1.1.0      
jupyterlab             2.1.4         
jupyterlab-server      1.1.5    
```

After adding the missing req it worked like a charm. :)

**Comment by LukeAI** [comment]
thanks for posting solution @octavd 
I had same problem, this sorted it.

**Comment by SeaRealE** [comment]
> I've found a solution to make it work.
> I was missing from `pip` -> `tensorboard`
> 
> Here you can find the requirements:
> 
> ```
> tensorflow==2.1.0
> jupyter-tensorboard==0.2.0
> tensorflow-estimator==2.1.0
> tensorboard==2.1.0
> ```
> 
> And for `jupyter`:
> 
> ```
> jupyter-client         6.1.3      
> jupyter-core           4.6.3      
> jupyter-kernel-gateway 2.4.0      
> jupyter-telemetry      0.1.0      
> jupyter-tensorboard    0.2.0      
> jupyterhub             1.1.0      
> jupyterlab             2.1.4         
> jupyterlab-server      1.1.5    
> ```
> 
> After adding the missing req it worked like a charm. :)

thanks for your solution @octavd
